# Backlight
light:
  - platform: monochromatic
    name: Backlight
    id: backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s
    internal: true

# Turn backlight on at boot
automation:
  - on_boot:
      priority: 600
      then:
        - light.turn_on: backlight
        - logger.log: "Backlight turned on at boot"

# Screensaver Presence Trigger
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.office_presence_group
    on_press:
      - lvgl.resume:
      - delay: 10ms
      - switch.turn_on: backlight
      - logger.log: "Screensaver is turned off"

    on_release:
      - switch.turn_off: backlight
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on"